version: '3'

services:
  service:
    container_name: "scoring_api"
    image: scoring_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      PYTHONUNBUFFERED: 1
      SERVICE_HOST: "0.0.0.0"
      SERVICE_PORT: 8080
    networks:
        - custom
    depends_on:
        - redis
  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - custom
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=qwerty
    ports:
      - "8081:8081"
    networks:
      - custom
    depends_on:
      - redis

volumes:
  redis:
  redis-config:

networks:
  custom:
    driver: bridge